### ISSUE TITLE
[1.0.0] Hangs on orange led 

### ISSUE THREAD

**Issue by piciuok** [avdeevsv91/mjsxj02hl_application#1]
Hey,

I try to flash firmware like in instruction from here: https://io-net.ru/mjsxj02hl_firmware/

How i flashed it? 
Files moved directly on sdcard, camera off, card in.
Device after on hanged for while, orange light turned on, after 1 second white led turned on, so i released reset button. Waited about 20 seconds, camera restarts and...hang on orange led. Nothing had happen after 10 minuts, so i flashed previous firmware and camera now works on original firmware. 

Have you any idea how to do it correctly? 

I`m "standard" user (without skills to make that amazing things like you!)

**Comment by avdeevsv91** [comment]
Wi-Fi access point available after a reboot?

**Comment by piciuok** [comment]
I scanned for within that 10 minutes and no any new network appears on phone. I was try enter "new network" by SSID to force connection (first thought - maybe it's just hidden network) but without result.
On original firmware LED turns orange too but after few seconds it starts working.

**Comment by avdeevsv91** [comment]
Try setting the wi-fi connection parameters using the wpa_supplicant.conf file on the sd-card:
```
network={
    scan_ssid=1
    ssid="network_name"
    psk="network_password"
}
```

**Comment by NikDevx** [comment]
У меня такая же проблема.
Создание файла не помогло.

Не цепляется к Wi-Fi.

**Comment by NikDevx** [comment]
> Hey,
> 
> I try to flash firmware like in instruction from here: https://io-net.ru/mjsxj02hl_firmware/
> 
> How i flashed it?
> Files moved directly on sdcard, camera off, card in.
> Device after on hanged for while, orange light turned on, after 1 second white led turned on, so i released reset button. Waited about 20 seconds, camera restarts and...hang on orange led. Nothing had happen after 10 minuts, so i flashed previous firmware and camera now works on original firmware.
> 
> Have you any idea how to do it correctly?
> 
> I`m "standard" user (without skills to make that amazing things like you!)

Try to put a full dump (full-dump 4.0.05-0105), and then install the firmware.  
It helped me
