### ISSUE TITLE
Copy record data from sdcard to server 

### ISSUE THREAD

**Issue by NikDevx** [avdeevsv91/mjsxj02hl_application#4]
Is it possible to implement as here?
https://github.com/hetzbh/yi-cams-backup

**Comment by avdeevsv91** [comment]
Currently, saving videos to an SD card is not implemented.

**Comment by tiimsvk** [comment]
Do you plan to add this setting (preferably with motion detection but it can also be set in HA)? Then it would be a full-fledged replacement for the original xiaomi SW.
I have 5 of these cameras and I am currently using them at home. The reliability of the xiaomi cn server is very poor.

**Comment by avdeevsv91** [comment]
This is not planned for the near future. You can implement this yourself and make a pr.
